[package]
name = "cRypto"
version = "0.2.0"
edition = "2024"

[dependencies]
ascon-hash = "0.3.1"
argon2 = "0.5.3"
hex = "0.4.3"
clap = { version = "4.5.53", features = ["derive"] }
rand = "0.9.2"
thiserror = "2.0.17"
hardware-query = "0.2.1"
sha2 = "0.10.9"
